// code generated by Bricx Command Center
#include <config.h>
#include <dsound.h>

static const note_t music[] = {
  { PITCH_PAUSE, 120 },
  { PITCH_Gm4, 1 },
  { PITCH_PAUSE, 7 },
  { PITCH_E5, 2 },
  { PITCH_PAUSE, 8 },
  { PITCH_D6, 1 },
  { PITCH_PAUSE, 7 },
  { PITCH_Fm6, 6 },
  { PITCH_PAUSE, 8 },
  { PITCH_END, 0 }
};

int main(int argc,char *argv[]) {
  dsound_set_duration(10);
  dsound_play(music);
  return 0;
}

